#!/bin/bash

actual=`cat /sys/class/backlight/nv_backlight/brightness`

nuevo=$(($actual-10))

( (( $nuevo > 0 )) && sudo sh -c "echo $nuevo > /sys/class/backlight/nv_backlight/brightness" ) || sudo sh -c "echo 1 > /sys/class/backlight/nv_backlight/brightness"
